version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/migration.sql:/docker-entrypoint-initdb.d/migration.sql

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
      KEYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_REALM: myrealm
      KEYCLOAK_CLIENT_ID: myclient
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    command: python -m flask run --host=0.0.0.0 --port=5000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=https://maski.strupino.pl/api
      - REACT_APP_KEYCLOAK_URL=http://keycloak:8080/auth
      - REACT_APP_KEYCLOAK_REALM=myrealm
      - REACT_APP_KEYCLOAK_CLIENT_ID=myclient
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminpassword
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
